#!/bin/sh
#gfortran -c -o bbhw.o bbhw.f
#gfortran -mips2 bbhw.o vegas_en.o mstwpdf.o alphaS.o -o bbhw.x
#./bbhw.x


for i in `seq 1 20`
do
        num=$((19 + $i))
        arg=$num
        sed -i 2s/.*/"$arg"/ bbhw.dat
        ./bbhw.x
#        echo $arg
#        cat gutg.dat
done
