#!/bin/sh
gfortran -c -o bbhh.o bbhh.f
gfortran -mips2 bbhh.o vegas_en.o mstwpdf.o alphaS.o -o bbhh.x
./bbhh.x

#decimal=".d0"

#for i in `seq 1 50`
#do
#        num=$((200 + 16 *$i))
#        arg=$num$decimal
#        sed -i 6s/.*/"$arg"/ bbhw.dat
#        ./bbhw.x
#        echo $arg
#        cat gutg.dat
#done
